// Regenerates the "Feature catalogue" section of README.md from the
// vendored library metadata, so the pickable feature/alias vocabulary is
// documented next to the config that names it.
//
// Usage (from the repo root):
//
//   node scripts/feature-catalogue.ts
//
// Reads the library version from polyfill.toml, walks
// polyfill-libraries/<version>/*/meta.json, and rewrites the README
// between the CATALOGUE markers. Run it after vendoring a new library
// version.

import fs from 'node:fs/promises';

const root = new URL('..', import.meta.url);

const toml = await fs.readFile(new URL('polyfill.toml', root), 'utf-8');
const version = /^version = "([^"]+)"/m.exec(toml)?.[1];
if (!version) throw new Error('polyfill.toml names no library version');

const libDir = new URL(`polyfill-libraries/${version}/`, root);
const entries = (await fs.readdir(libDir, { withFileTypes: true }))
  .filter(e => e.isDirectory() && !e.name.startsWith('_'))
  .map(e => e.name)
  .sort();

type Meta = { aliases?: string[]; isPublic: boolean };
const metas = new Map<string, Meta>();
for (const name of entries) {
  const meta: Meta = JSON.parse(
    await fs.readFile(new URL(`${name}/meta.json`, libDir), 'utf-8')
  );
  if (typeof meta.isPublic !== 'boolean') {
    throw new Error(`unexpected meta.json shape for ${name}`);
  }
  metas.set(name, meta);
}

const publics = entries.filter(name => metas.get(name)?.isPublic);

// The bundle vocabulary: the curated `default` set, `dom4` and the yearly
// es* sets. meta.json alias arrays also carry internal names (default-3.x,
// modernizr:*, blissfuljs) that are not part of it.
const aliasRe = /^(default|dom4|es(5|6|7|20\d\d))$/;
const aliasMembers = new Map<string, string[]>();
for (const name of publics) {
  for (const alias of metas.get(name)?.aliases ?? []) {
    if (aliasRe.test(alias)) {
      aliasMembers.set(alias, [...(aliasMembers.get(alias) ?? []), name]);
    }
  }
}

const aliased = new Set([...aliasMembers.values()].flat());
const standalone = publics.filter(name => !aliased.has(name));

// Per-locale sub-polyfills (`Intl.*.~locale.<tag>`) are one entry each in
// the library; one line per family keeps the list readable.
const localeFamilies = new Map<string, number>();
const singles: string[] = [];
for (const name of standalone) {
  const family = /^(.*\.~locale)\./.exec(name)?.[1];
  if (family) {
    localeFamilies.set(family, (localeFamilies.get(family) ?? 0) + 1);
  } else {
    singles.push(name);
  }
}

const aliasBlocks = [...aliasMembers.keys()]
  .sort()
  .map(alias => {
    const members = aliasMembers.get(alias) ?? [];
    return `<details><summary><code>${alias}</code> (${members.length} polyfills)</summary>

${members.map(m => `- \`${m}\``).join('\n')}

</details>`;
  })
  .join('\n\n');

const singleLines = [
  ...singles.map(s => `- \`${s}\``),
  ...[...localeFamilies].sort().map(
    ([family, count]) => `- \`${family}.<tag>\` (${count} locales)`
  ),
].join('\n');

const section = `Library ${version}: ${publics.length} public features. Regenerated by \`node scripts/feature-catalogue.ts\` — run it after vendoring a new library version.

**Aliases** — one name pulls in the whole set (UA targeting still applies per polyfill):

${aliasBlocks}

**Standalone features** — name them individually:

${singleLines}`;

const readmeUrl = new URL('README.md', root);
const readme = await fs.readFile(readmeUrl, 'utf-8');
const markers = /<!-- CATALOGUE_START -->[\s\S]*?<!-- CATALOGUE_END -->/;
if (!markers.test(readme)) {
  throw new Error('README.md is missing the CATALOGUE_START/END markers');
}
const updated = readme.replace(
  markers,
  `<!-- CATALOGUE_START -->\n${section}\n<!-- CATALOGUE_END -->`
);
if (updated !== readme) {
  await fs.writeFile(readmeUrl, updated, 'utf-8');
  console.log(`README.md catalogue updated for library ${version}`);
} else {
  console.log(`README.md catalogue is already up to date`);
}
